### ISSUE TITLE
station coordinates ?

### ISSUE THREAD

**Issue by alfonsodev** [kr1sp1n/bvg-api#1]
Hi would it be posible to expose the station coordinates? 
Thanks.

**Comment by alfonsodev** [comment]
I found this resource http://daten.berlin.de/datensaetze/vbb-fahrplandaten-dezember-2015-bis-dezember-2016
stops.txt contains coordinates by station id.

**Comment by derhuerst** [comment]
Maybe [vbb-static](https://github.com/derhuerst/vbb-static) will help you. It has the same data as the dump on `daten.berlin.de`, but in a more comfortable format. Its dependency, [vbb-gtfs](https://github.com/derhuerst/vbb-gtfs) is not up to date (~ mid of 2015), but the conversion script from GTFS to ndjson probably still works.

EDIT: [vbb-gtfs](https://github.com/derhuerst/vbb-gtfs) is up to date now.

**Comment by kr1sp1n** [comment]
@alfonsodev looks pretty straight forward. will work on that asap, thanx :smile:

**Comment by kr1sp1n** [comment]
@alfonsodev Ok, now you get back a location object for every station like this:

``` json
{
  "id": "9100003",
  "name": "S+U Alexanderplatz Bhf (Berlin)",
  "href": "http://localhost:3000/station/9100003",
  "location": {
    "lat": "52.5215120",
    "lon": "13.4112670"
  }
}
```

See https://bvg-api.herokuapp.com/station/9100003 as a live example.
I just parse the locations from the stops.txt CSV file when the API starts and extend
every station with that data.
Thanks for your help! :+1: 

Are you happy with that?

**Comment by alfonsodev** [comment]
Thanks @kr1sp1n for the update, very happy with it :)
@derhuerst good to know that extra info thanks

**Comment by derhuerst** [comment]
> I just parse the locations from the stops.txt CSV file when the API starts and extend every station with that data.

Check out [`vbb-stations`](https://github.com/derhuerst/vbb-stations)! (;
