### ISSUE TITLE
Request for limited number of departures

### ISSUE THREAD

**Issue by deg0nz** [kr1sp1n/bvg-api#4]
Hi,
first of all: Good work, thanks for the API! :)

**Is it possible to pull just a few JSON Objects from the server within the request URL?**

For example:
I want to get only the next 5 departures for my station to avoid an data overhead with all the other departure times, but query the server more often for departures in the near future to get an up-to-date list. (Alexanderplatz and Frankfurter Allee for example return many many objects)

My goal is: I want to write a BVG-Plugin for the [MagicMirror Project](https://github.com/MichMich/MagicMirror)
For that, only a limited number of the next departures is needed.
I could get the whole output and get the first 5 objects of the array, but it's a waste of bandwidth in my optinion...

Greetz!
B.

**Comment by derhuerst** [comment]
[`vbb-hafas` already does this](https://github.com/derhuerst/vbb-hafas/blob/36d4d31/lib/departures.js#L65). You could either use that one directly (although one needs an API) or copy the code.

**Comment by deg0nz** [comment]
Ah, yeah. That looks nice! I didn't even know, that a thing like HAFAS even exists.
I'll give it a try.

Thanks, @derhuerst
