### ISSUE TITLE
Correct naming for stops.txt

### ISSUE THREAD

**Issue by NKjoep** [kr1sp1n/bvg-api#5]
Hallo! 

It would be nice if you could rename `stops.txt` into `stops.csv`.

Github has also a very nice ui for csv files.

Cheers!

**Comment by derhuerst** [comment]
It looks like the naming is taken from the [GTFS standard](https://developers.google.com/transit/gtfs/reference/). I think it makes sense to keep like it is.

**Comment by kr1sp1n** [comment]
Agree. @NKjoep if you wanna have nice UI for CSV files then download it and open it with a nice program on your local machine 😉
