### ISSUE TITLE
Realtime Data

### ISSUE THREAD

**Issue by zaphbbrox** [kr1sp1n/bvg-api#6]
Hey,
I'm not sure how to fetch the realtime data. I saw there is the `?realtime` parameter, but I don't know how to use it.

Tried all imaginable urls like:
- localhost:3000/station?realtime/STATION_ID
- localhost:3000/station/?realtime/STATION_ID

and so on..

Would be nice if you point me into the right direction =)
Great work by the way!

**Comment by vied12** [comment]
Hi @zaphbbrox 
Have you tried `station/STATION_ID?realtime=true` ?

**Comment by derhuerst** [comment]
I noticed `https://bvg-api.herokuapp.com/station?input=alexanderplatz` returns `200 Ok` with an empty response. I therefore bluntly advocate using [`transport.rest`](https://github.com/derhuerst/vbb-rest/blob/master/docs/index.md#berlin--brandenburg-public-transport-api). 😄

**Comment by vied12** [comment]
When I run the application somewhere else it is still working. I guess the
bvg has blacklisted heroku...
But thanks for the link, I didn't know this one. I could give a try soon.
